"""initial schema

Revision ID: 56b166236dbc
Revises: 
Create Date: 2026-03-24 21:55:37.534769

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '56b166236dbc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('industries',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('display_color', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('raw_content',
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('subreddit', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_raw_content_hash', 'raw_content', ['content_hash'], unique=False)
    op.create_index('idx_raw_content_ingested_at', 'raw_content', [sa.literal_column('ingested_at DESC')], unique=False)
    op.create_index('idx_raw_content_source', 'raw_content', ['source'], unique=False)
    op.create_index('idx_raw_content_unprocessed', 'raw_content', ['is_processed'], unique=False, postgresql_where=sa.text('NOT is_processed'))
    op.create_table('ai_briefings',
    sa.Column('briefing_type', sa.String(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('industry_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('key_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_analyzed', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_briefings_company', 'ai_briefings', ['company_id', sa.literal_column('generated_at DESC')], unique=False)
    op.create_index('idx_briefings_type_date', 'ai_briefings', ['briefing_type', sa.literal_column('generated_at DESC')], unique=False)
    op.create_table('anomaly_alerts',
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('industry_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('baseline_value', sa.Float(), nullable=True),
    sa.Column('z_score', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_anomaly_active', 'anomaly_alerts', ['is_active', sa.literal_column('triggered_at DESC')], unique=False)
    op.create_index('idx_anomaly_company', 'anomaly_alerts', ['company_id', sa.literal_column('triggered_at DESC')], unique=False)
    op.create_table('company_industries',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('industry_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'industry_id')
    )
    op.create_table('entity_mentions',
    sa.Column('raw_content_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('mention_text', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_content_id'], ['raw_content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_content_id', 'company_id')
    )
    op.create_index('idx_entity_mentions_company', 'entity_mentions', ['company_id'], unique=False)
    op.create_index('idx_entity_mentions_content', 'entity_mentions', ['raw_content_id'], unique=False)
    op.create_table('entity_relations',
    sa.Column('company_a_id', sa.UUID(), nullable=False),
    sa.Column('company_b_id', sa.UUID(), nullable=False),
    sa.Column('co_occurrence_count', sa.Integer(), nullable=False),
    sa.Column('sentiment_correlation', sa.Float(), nullable=True),
    sa.Column('period_type', sa.String(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('company_a_id < company_b_id', name='ck_canonical_order'),
    sa.ForeignKeyConstraint(['company_a_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_b_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_a_id', 'company_b_id', 'period_type', 'period_start')
    )
    op.create_index('idx_entity_rel_company_a', 'entity_relations', ['company_a_id'], unique=False)
    op.create_index('idx_entity_rel_company_b', 'entity_relations', ['company_b_id'], unique=False)
    op.create_table('predictive_signals',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('signal_type', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('sentiment_window_days', sa.Integer(), nullable=False),
    sa.Column('correlation', sa.Float(), nullable=True),
    sa.Column('lag_hours', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pred_company', 'predictive_signals', ['company_id', sa.literal_column('generated_at DESC')], unique=False)
    op.create_table('price_data',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('daily_return', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'date')
    )
    op.create_index('idx_price_company_date', 'price_data', ['company_id', sa.literal_column('date DESC')], unique=False)
    op.create_table('sentiment_aggregates',
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('industry_id', sa.UUID(), nullable=True),
    sa.Column('period_type', sa.String(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('avg_score', sa.Float(), nullable=False),
    sa.Column('median_score', sa.Float(), nullable=True),
    sa.Column('score_stddev', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('reddit_avg', sa.Float(), nullable=True),
    sa.Column('reddit_volume', sa.Integer(), nullable=False),
    sa.Column('news_avg', sa.Float(), nullable=True),
    sa.Column('news_volume', sa.Integer(), nullable=False),
    sa.Column('twitter_avg', sa.Float(), nullable=True),
    sa.Column('twitter_volume', sa.Integer(), nullable=False),
    sa.Column('momentum', sa.Float(), nullable=True),
    sa.Column('acceleration', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'industry_id', 'period_type', 'period_start')
    )
    op.create_index('idx_agg_company_period', 'sentiment_aggregates', ['company_id', 'period_type', sa.literal_column('period_start DESC')], unique=False)
    op.create_index('idx_agg_industry_period', 'sentiment_aggregates', ['industry_id', 'period_type', sa.literal_column('period_start DESC')], unique=False)
    op.create_table('sentiment_scores',
    sa.Column('raw_content_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('finbert_positive', sa.Float(), nullable=True),
    sa.Column('finbert_negative', sa.Float(), nullable=True),
    sa.Column('finbert_neutral', sa.Float(), nullable=True),
    sa.Column('finbert_label', sa.String(), nullable=True),
    sa.Column('llm_score', sa.Float(), nullable=True),
    sa.Column('llm_label', sa.String(), nullable=True),
    sa.Column('llm_reasoning', sa.Text(), nullable=True),
    sa.Column('ensemble_score', sa.Float(), nullable=False),
    sa.Column('ensemble_label', sa.String(), nullable=False),
    sa.Column('ensemble_confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raw_content_id'], ['raw_content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sentiment_company', 'sentiment_scores', ['company_id'], unique=False)
    op.create_index('idx_sentiment_company_time', 'sentiment_scores', ['company_id', sa.literal_column('scored_at DESC')], unique=False)
    op.create_index('idx_sentiment_label', 'sentiment_scores', ['ensemble_label'], unique=False)
    op.create_index('idx_sentiment_scored_at', 'sentiment_scores', [sa.literal_column('scored_at DESC')], unique=False)
    op.create_index('idx_sentiment_source', 'sentiment_scores', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sentiment_source', table_name='sentiment_scores')
    op.drop_index('idx_sentiment_scored_at', table_name='sentiment_scores')
    op.drop_index('idx_sentiment_label', table_name='sentiment_scores')
    op.drop_index('idx_sentiment_company_time', table_name='sentiment_scores')
    op.drop_index('idx_sentiment_company', table_name='sentiment_scores')
    op.drop_table('sentiment_scores')
    op.drop_index('idx_agg_industry_period', table_name='sentiment_aggregates')
    op.drop_index('idx_agg_company_period', table_name='sentiment_aggregates')
    op.drop_table('sentiment_aggregates')
    op.drop_index('idx_price_company_date', table_name='price_data')
    op.drop_table('price_data')
    op.drop_index('idx_pred_company', table_name='predictive_signals')
    op.drop_table('predictive_signals')
    op.drop_index('idx_entity_rel_company_b', table_name='entity_relations')
    op.drop_index('idx_entity_rel_company_a', table_name='entity_relations')
    op.drop_table('entity_relations')
    op.drop_index('idx_entity_mentions_content', table_name='entity_mentions')
    op.drop_index('idx_entity_mentions_company', table_name='entity_mentions')
    op.drop_table('entity_mentions')
    op.drop_table('company_industries')
    op.drop_index('idx_anomaly_company', table_name='anomaly_alerts')
    op.drop_index('idx_anomaly_active', table_name='anomaly_alerts')
    op.drop_table('anomaly_alerts')
    op.drop_index('idx_briefings_type_date', table_name='ai_briefings')
    op.drop_index('idx_briefings_company', table_name='ai_briefings')
    op.drop_table('ai_briefings')
    op.drop_index('idx_raw_content_unprocessed', table_name='raw_content', postgresql_where=sa.text('NOT is_processed'))
    op.drop_index('idx_raw_content_source', table_name='raw_content')
    op.drop_index('idx_raw_content_ingested_at', table_name='raw_content')
    op.drop_index('idx_raw_content_hash', table_name='raw_content')
    op.drop_table('raw_content')
    op.drop_table('industries')
    op.drop_table('companies')
    # ### end Alembic commands ###
